In [3]:
import numpy as np


In [4]:
# Create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Matrix Addition
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4],[3, 2, 1]])
result1 = matrix1 + matrix2
print("Matrix Addition Results")
print(result1)

# Matrix Multiplication
result2 = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication Results")
print(result2)

# Perform element-wise matrix division
result3 = np.divide(matrix1, matrix2)
print("\nElement-wise Matrix Division ReSults")
print(result3)


Matrix Addition Results
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication Results
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Matrix Division ReSults
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [10]:
# Indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0, 1])  # Access element at row 0, column 1


2


In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing
sub_matrix = matrix[:, 1:3]  # Slice all rows, columns 1 to 2
print(sub_matrix)

[[2 3]
 [5 6]
 [8 9]]


In [12]:
# Applying functions to all elements
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
square_matrix = np.square(matrix)
print(square_matrix)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flattening the matrix
flattened_array = matrix.flatten()

print("Original Matrix:")
print(matrix)

print("\nFlattened Array:")
print(flattened_array)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened Array:
[1 2 3 4 5 6 7 8 9]
